FXlist = {
  Instruments = {
    "Muon Tau",
    "Kontakt",
    "Play",
    "VacuumPro",
    "FM8",
    "Massive",
    "Reaktor 6",
    "Oatmeal",
    "Z3TA+2",
    "Firebird",
    "SQ8L",
    "Absynth 5",
    "Tyrell N6",
    "Zebralette",
    "Podolski",
    "Hybrid",
    "mda SubSynth",
    "Crystal",
    "Rapture",
    "Claw",
    "DX10",
    "JX10",
    "polyIblit",
    "dmiHammer"
  },
  Drums = {
    "Battery4",
    "VSTi: Kontakt 5 (Native Instruments GmbH) (16 out)",
    "Kickbox",
  },
  Effects = {
    EQ = {
      "ReaEq",
	"Cheby24db",
     "BootEQmkII",
      "VST3: OneKnob Phatter Stereo"
    },
    Filter = {
      "BiFilter",
      "MComb",
      "AtlantisFilter",
      "ReaFir",
      "Apple 12-Pole Filter",
      "Apple 2-Pole Lowpass Filter",
      "Chebyshev 4-Pole Filter",
      "JS: Exciter",
    },
   Modulation = {
      "Chorus (Improved Shaping)",
      "Chorus (Stereo)",
      "Chorus CH-1",
      "Chorus CH-2",
      "VST3: MFlanger",
      "VST3: MVibrato",
      "VST3: MPhaser",
      "VST3: Tremolo",
    },
    Dynamics = {
      "VST3: API-2500 Stereo",
      "VST3: L1 limiter Stereo",
      "VST3: TransX Wide Stereo",
      "VST3: TransX Multi Stereo",
      "ReaComp",
      "ReaXComp",
      "VST3:Percolate",
    },
    Distortion = {
      "Amplitube 3",
      "Renegade",
      "VST3: MSaturator", 
       "VST3: MWaveShaper",
     "VST3: MWaveFolder",
      "Guitar Rig 5",
      "Cyanide 2",
      "Driver",
	"Revalver HPSE",
    },
    Reverb = {
      "ReaVerb",
      "VST3: IR-L fullStereo",
      "VST3: H-Reverb Stereo/5.1",
      "VST3: H-Reverb long Stereo/5.1",
      "VST3: RVerb Stereo",
      "epicVerb",
      "Ambience",
      "Hexaline",
      "ModernFlashVerb",
    },
    Delay = {
      "ReaDelay",
      "VST3: H-Delay Stereo",
      "VST3: STADelay",
      "MjRotoDelay",
      "ModernSpacer",
    },
    Mastering = {
      "VST3: Drawmer S73",
      "VST3: L1+ Ultramaximizer Stereo",
      "VST3: Elephant",
    },
    Strip = {
      "VST3: Scheps OmniChannel Stereo",
      "VST3: SSLGChannel Stereo",
    },
    Stereo = {
      "VST3: S1 Imager Stereo",
      "VST3: MSpectralPan",
      "VST3: MStereoExpander",
      "VST3: Propane",
      "Saike StereoManipulator",
    },
    Gate = {
      "ReaGate",
    },
    Pitch = {
      "ReaPitch",
      "ReaTune",
    },
    Vocoder = {
      "mda Talkbox",
    },
    Analysis = {
      "SideSpectrum Meter"
    },
  },
}
